# Generated by Django 4.1.1 on 2022-09-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIC_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='plan_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
