# Generated by Django 4.1.1 on 2022-09-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIC_API', '0002_datastore_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='plan_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
