# Generated by Django 4.1.1 on 2022-09-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIC_API', '0003_alter_datastore_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='report_data',
            field=models.URLField(),
        ),
    ]
